#version: '3.7'
#
#services:
#
#  sample-prod:
#    container_name: sample-prod
#    build:
#      context: .
#      dockerfile: Dockerfile.prod
#    ports:
#      - '1337:80'

# Development docker-compose:
#version: '3.7'
#
#services:
#
#  sample:
#    container_name: sample
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - '.:/app'
#      - '/app/node_modules'
#    ports:
#      - 3001:3000